update

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -14,3 +14,10 @@ fi
 
 
 python3 "$PYFILE"
+
+if [ $? -ne 0 ]; then
+    echo "Error: Python script failed to execute."
+    exit 1
+fi
+
+exit 0
